config/routes.rb
Rails.application.routes.draw do

	
  	get 'welcome/index'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  		resources :articles do
  			resources :comments
  		end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "hbt", password: "secreto", except: [:index, :show]

	def index
    	@articles = Article.all
  	end

	def show
    	@article = Article.find(params[:id])
  	end

	def new
		@article = Article.new
	end

	def edit
  		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
 
		if @article.save
			redirect_to @article
		else
			render 'Novo'
		end
	end

	def update
  		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
    		redirect_to @article
  		else
    		render 'Editar'
  		end
	end

	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy
 
 		redirect_to articles_path
	end
 
	private
  		def article_params
    		params.require(:article).permit(:title, :text)
  	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "hbt", password: "secreto", only: :destroy

	def create
    	@article = Article.find(params[:article_id])
    	@comment = @article.comments.create(comment_params)
    	redirect_to article_path(@article)
  	end

  	def destroy
    	@article = Article.find(params[:article_id])
    	@comment = @article.comments.find(params[:id])
    	@comment.destroy
    	redirect_to article_path(@article)
  	end
 
  	private
    	def comment_params
      		params.require(:comment).permit(:commenter, :body)
    	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :text, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :text, :class => 'form-control' %>
    </div>
    <%=f.error_span(:text) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editar artigo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Voltar', articles_path %>


<!--<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>-->

app/views/articles/index.html.erb
<h1>Listando Artigos</h1>
<%= link_to 'Novo artigo', new_article_path %>

<table>
  <tr>
    <th>Títulos</th>
    <th>Textos</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Ver', article_path(article) %></td>
      <td><%= link_to 'Editar', edit_article_path(article) %></td>
      <td><%= link_to 'Apagar', article_path(article),
              method: :delete,
              data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Novo Artigo</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<dir class="container">
  <div class="page-header">
    <h1>Artigo</h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong>Título:</strong></dt>
    <dd><%= @article.title %></dd>
    <dt><strong>Texto:</strong></dt>
    <dd><%= @article.text %></dd>
  </dl>


  <%= link_to t('.back', :default => t("helpers.links.back")),
                articles_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_article_path(@article), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                article_path(@article),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <br/> <br/>
  <hr size = 7>
  <br/> <br/>
  <br/> <br/>
  <div class="page-header">
    <h3>Comentários</h3>
  </div>
  <%= render @article.comments %>

  <h3>Adicionar um comentário:</h3>
  <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :Usuário%><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :comentário %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</dir>

app/views/comments/_comment.html.erb

<table class="table table-striped">
	<p>
  		<strong>Usuário:</strong>
  		<%= comment.commenter %>
	</p>
 	<p>
  		<strong>Comentário:</strong>
  		<%= comment.body %>
  	</p>

  		<%= link_to 'Apagar comentário', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Você tem certeza?' } %>
    <p>
	</p>	
</table>


app/views/comments/_form.html.erb
<%= form_for @comment, :html => { :class => "form-horizontal comment" } do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :commenter, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :commenter, :class => 'form-control' %>
    </div>
    <%=f.error_span(:commenter) %>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :body, :class => 'form-control' %>
    </div>
    <%=f.error_span(:body) %>
  </div>
  <div class="form-group">
    <%= f.label :article_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :article_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:article_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comments_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:commenter) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:article_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.article_id %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      comment_path(comment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.novo', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:commenter) %>:</strong></dt>
  <dd><%= @comment.commenter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @comment.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:article_id) %>:</strong></dt>
  <dd><%= @comment.article_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog do Hugo" %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'blog.ico', rel: 'shortcut icon' %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--Imagem que volta para home-->
        <a class="navbar-brand" href="/">
                <%= image_tag "blog_hugo.png", width: '110px', style: 'margin-top: -7px' %>
        </a>
        <!--<a class="navbar-brand" href="#">Blog</a>-->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Matérias 1", "/articles/1"  %></li>
            <li><%= link_to "Matérias 2", "/articles/2"  %></li>
            <li><%= link_to "Matérias 3", "/articles/3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <!--inicia o index da página-->
    <%= bootstrap_flash %>
    <%= yield %>



<% if false %>
comentário do if al end
trecho de código para adicionar uma sidebar!
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>      
      </div>
    </div>
<% end %>
    

        <footer class="footer" id="footer_application">
            <div class="container">
                <br/>
                <p style="text-align:center;">
                    <strong>&copy; 2019 <a href="/index" target="_blank" onclick="javascript: return false">Blog do Hugo</a>.</strong> Desenvolvido por STW Online.
                    <strong>Versão:</strong> 3
                </p>
            </div>
        </footer>

  </body>
</html>

app/views/welcome/index.html.erb
<div class= "container">
    <div class= "jumbotron">
        <h1>Bem vindo ao Blog do Hugo</h1>
        <p>Sistema Web desenvolvido por STW Online</p>
        <p>
            <a class="btn btn-info btn-lg" href="/articles">Matérias</a>
        </p>
    </div>
</div>

<!--<h1>Bem vindo ao Blog do Hugo</h1>
<%= link_to 'Meu Blog', controller: 'articles' %>-->